/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "outline": "#948e9c",
        "primary-container": "#6750a4",
        "surface-dim": "#141218",
        "surface-variant": "#36343a",
        "surface-tint": "#cfbcff",
        "secondary-container": "#4d4465",
        "on-secondary-fixed-variant": "#4b4263",
        "surface-container-low": "#1d1b20",
        "error-container": "#93000a",
        "tertiary-fixed": "#ffdf93",
        "on-primary": "#381e72",
        "surface-container": "#211f24",
        "on-secondary": "#342b4b",
        "surface-container-highest": "#36343a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed": "#241a00",
        "on-surface": "#e6e0e9",
        "on-primary-fixed": "#22005d",
        "surface": "#141218",
        "surface-container-lowest": "#0f0d13",
        "tertiary": "#e7c365",
        "surface-container-high": "#2b292f",
        "on-primary-container": "#e0d2ff",
        "tertiary-container": "#c9a74d",
        "inverse-surface": "#e6e0e9",
        "error": "#ffb4ab",
        "tertiary-fixed-dim": "#e7c365",
        "inverse-primary": "#6750a4",
        "secondary": "#cdc0e9",
        "surface-bright": "#3b383e",
        "primary-fixed": "#e9ddff",
        "primary-fixed-dim": "#cfbcff",
        "primary": "#cfbcff",
        "on-tertiary-container": "#503d00",
        "secondary-fixed-dim": "#cdc0e9",
        "on-primary-fixed-variant": "#4f378a",
        "inverse-on-surface": "#322f35",
        "background": "#141218",
        "on-secondary-fixed": "#1f1635",
        "outline-variant": "#494551",
        "secondary-fixed": "#e9ddff",
        "on-tertiary": "#3e2e00",
        "on-tertiary-fixed-variant": "#594400",
        "on-secondary-container": "#bfb2da",
        "on-surface-variant": "#cbc4d2",
        "on-background": "#e6e0e9",
        "neon-lime": "#AAFF00",
        "neon-coral": "#FF5C5C",
        "neon-cyan": "#00FFFF"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "margin": "24px",
        "unit": "4px",
        "gutter": "16px",
        "xl": "40px",
        "xs": "4px",
        "md": "16px",
        "sm": "8px",
        "lg": "24px"
      },
      "fontFamily": {
        "body-reg": ["IBM Plex Mono"],
        "data-md": ["IBM Plex Mono"],
        "h1": ["Syne"],
        "h2": ["Syne"],
        "code-sm": ["IBM Plex Mono"],
        "data-lg": ["IBM Plex Mono"],
        "display-xl": ["Syne"],
        "label-caps": ["IBM Plex Mono"]
      },
      "fontSize": {
        "body-reg": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "data-md": ["16px", { "lineHeight": "20px", "fontWeight": "500" }],
        "h1": ["48px", { "lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "h2": ["32px", { "lineHeight": "32px", "fontWeight": "700" }],
        "code-sm": ["10px", { "lineHeight": "12px", "fontWeight": "400" }],
        "data-lg": ["24px", { "lineHeight": "24px", "fontWeight": "600" }],
        "display-xl": ["80px", { "lineHeight": "72px", "letterSpacing": "-0.04em", "fontWeight": "800" }],
        "label-caps": ["12px", { "lineHeight": "12px", "fontWeight": "700" }]
      }
    }
  },
  plugins: [],
}
